### ISSUE TITLE
Feat: Add content to Resources (Further Reading) Page

### ISSUE THREAD

**Issue by noxxaz** [poly-zero/polyzero#137]
Resources page should NOT have side-nav (Just like Landing Page)

In-page title should be "Further Reading" but page name can remain "Resources"
Page should include content here:
https://docs.google.com/document/d/1_4_Qsbi5wJx-JQ2ISA6NKksRiqtrDH_c7ejQf7FNTPE/edit

**Comment by 91Pudge** [comment]
Done
